:toc:
:icons: font

== Todo

check: https://github.com/yulonghu/vim-sensible

In what situations use:
CTRL-T : jump to [count] older entry in the tag stack (default 1).
CTRL-O
g-<Right mouse>
CTRL-<Right mouse>
CTRL-;  " tapé par inadvertance sur un tag

check last line
" vim:sts=2:sw=2:et:
:set softtabstops=2
:set shiftwidth=2
:set expandtab


== Compilation in Ubuntu


=== Creating original directory from a fork on Github

 cd ~/.vim
 git clone https://github.com/ahjun001-forks/vim.git
 mv vim src


=== Sync the github forked directory with its original /vim/vim.git

 git remote -v
    origin	https://github.com/ahjun001-forks/vim.git (fetch)
    origin	https://github.com/ahjun001-forks/vim.git (push)
    upstream	https://github.com/ahjun001-forks/vim.git (fetch)
    upstream	https://github.com/ahjun001-forks/vim.git (push)
git fetch upstream
git checkout master
git merge upstream/master
(git push)

=== Sync the local repository and compile

 cd .vim/src
 git pull
 make clean      # remove what make built
 make distclean  # includes ./configure 
 ./configure --enable-gui=gtk3
 make
 make test
 sudo make install

=== Making VIM the default editor on Linux

 sudo update-alternatives --install /usr/bin/editor editor /usr/local/bin/vim 100

== Useful forgotten commands

=== Both VIM and mscodevim

 u to undo one change, U to undo all the changes on a line

 CTR-O / CTRL-I to go to previous / next jump

 n next occurence same direction, N next occurence opposite direction, repeat N to keep in this opposite direction

 r replaces one character, R replaces until <ESC> (Replace mode)

 i_CTRL_T / i_CTRL_D adds / deletes  one shiftwidth of indent in the current line

 Normal mode: db & dB, when cursor is as beginning of a word, will delete the precedent word along with the space in between.

 Moving forward / backward just before a char 'c' on a line: tx / Tx
 ';' ',' repeats in the same / opposite direction

 "for a long text between parentheses", from anywhere in the middle, T" Ctrl-v ,    or    t" Ctrl-v ,    will select the inside of ""
 Ctrl-v-i "  as well.   Ctrl-v a "  will select the "" as well.
 
 When cursor on line, scrolling so that line shows 1rst on top is best done with zt
 Alternatively zz to have text scroll so that it shows in the middle, zb to have it at bottom
 H M L position the cursor on screen without scrolling.

 Alternatively :set nu rnu    and then n CTRL-E[nd] / n CTRL-Y[esterday] will scroll screen by n lines down / up

 */ # will match whole word the cursor is on forward / backward
 g* / g# will also match words containing the word the cursor is on, g.e.: when on 'the', g* will match then there and so on.
 
 ma to make a mark, 'a ('<SPACE>a with US-int'l keyboard) to scroll so that cursor is as col.1 of this mark's line.  `a to have it right on the mark.

 X stands for dh (delete character left of the cursor)

 In visual mode, having started in the middle of what should be selected, 'o' brings back the cursor to the other end of the selection for further selection.
 'O' moves to the other corner of the same line.

 ~ is an operator if :set top is set in VIM, then works as such for text-objects in codevim

 :ju(mps)  will display a jump list, can be navigate with the mouse in codevim
 :<n>Ctrl-O / <n>Ctrl-I jumps in VIM
 :cle(arjumps)

=== VIM only

 :helpgrep <subject>
 :cwindow  " to browse results
 :cnext / cprev to jump to next / previous result

 :e $MYVIMRC

 While reading help or manual :set nu rnu    is useful

 :bp / :bn   or CTRL-O / CTRL-I  to go to the previous / next buffer

 v motion :w FILENAME   saves the Visually selected lines in file FILENAME 

 :set hls  highlights searched char string, :noh temporarilly removes highlight

 :set ic  highlights incremental search

 :set list / :set nolist turns invisible characters on / off

 command line completion with <TAB> is especially useful for :help

 Normal mode: ZZ is equivalent to :wq   ZZ also closes the help window without exiting the program

 Searching for text \< and \> are special markers that match beginning and end of a word

 After listing buffers :ls  close buffer n   with :bdn

 <TABS> or Ctrl-I goes to next jump, Ctrl-O

 Like "dd" or "D" deletes a whole line, "cc" or "S" changes a whole line.  With :set ai    it keeps the existing indent (leading white space) though.

 In replace mode, started with R, Ctrl-y will copy chars from precedent line, <BS> or Ctrl-h will undo the replace, putting back chars from initial text.

== Lists

=== :jumps


=== :marks


== From Quick Reference: see quickref.txt  :help quickref


=== matchit-configure

Configuration is local to the buffer (buffers could be of different languages, so different matching pairs).  So use :let instead of :set

== Get specific help


=== Normal mode command

 :help command_name
 :help x " shows delete one charj

=== Visual mode command

 prepend help with v_
 :help v_command_name
 :help v_u   " {Visual}u makes highlighted text lower case



=== Insert mode command

 prepend help with i_
 :help i_command_name
 :help i_<Esc>   " écrire litéralement <Esc> pour sortir de Insert ou Replace mode

=== Command-line command

 prepend help with :
 :help :command_name
 :help :quit

=== Command-line editing

 prepend help with c_
 :help c_command_name  " how to edit in the lower-screen command line
 :help c_<Del>

=== VIM command argument

 prepend help with -
 :help -command_name
 :help -r

=== Options

 prepend with '
 :help 'option'
 :help 'textwidth'

=== Regular expression
 
 prepend with /
 :help /reg_ex
 :help /[   " shows help on searching for character ranges


== VIM

 :scriptnames  " to see what files & plugins are loaded at startup

 :new
 :put=execute('scriptnames')  " will write in the new file

 VSCode will check in Settings (Ctrl+comma)  Vim> Vimrc:Path for vimrc file



== vimrc / .vimrc

in Linux Mint,  ~/.vim/vimrc contains one line:

 source ~/Documents/GitHub/cheat-sheet_VIM/vimrc 

== Managing packages (many plugins in a directory) and plugins

 https://vimhelp.org/repeat.txt.html#packages
 https://vi.stackexchange.com/questions/9522/what-is-the-vim8-package-feature-and-how-should-i-use-it
 https://medium.com/@paulodiovani/installing-vim-8-plugins-with-the-native-pack-system-39b71c351fea
