:toc:
:icons: font

== Todo

check: https://github.com/yulonghu/vim-sensible

In what situations use:
CTRL-T : jump to [count] older entry in the tag stack (default 1).
CTRL-O
g-<Right mouse>
CTRL-<Right mouse>
CTRL-;  " tapé par inadvertance sur un tag

check last line
" vim:sts=2:sw=2:et:
:set softtabstops=2
:set shiftwidth=2
:set expandtab


== Compilation in Ubuntu

 cd .vim
 git clone https://github.com/ahjun001-forks/vim.git

 cd .vim/vim
 git pull
 make clean      # remove what make built
 make distclean  # includes ./configure 
 ./configure --enable-gui=gtk3
 make
 make test
 sudo make install

== Useful forgotten commands

=== Both VIM and mscodevim

 u to undo one change, U to undo all the changes on a line

 CTR-O / CTRL-I to go to previous / next jump

 n next occurence same direction, N next occurence opposite direction, repeat N to keep in this opposite direction

 r replaces one character, R replaces until <ESC> (Replace mode)

 i_CTRL_T / i_CTRL_D adds / deletes  one shiftwidth of indent in the current line

 Normal mode: db & dB, when cursor is as beginning of a word, will delete the precedent word along with the space in between.

 Moving forward / backward just before a char 'c' on a line: tx / Tx
 ';' ',' repeats in the same / opposite direction
 "for a long text between parentheses", from anywhere in the middle, T" Ctrl-v ,    or    t" Ctrl-v ,    will select the inside of ""
 When cursor on line, scrolling so that line is 1rst on top is best done with zt
 Alternatively zz to have text scroll so that it's in the middle, zb to have it at bottom
 H M L position the cursor on screen without scrolling.

 Alternatively :set nu rnu    and then n CTRL-E[nd] / n CTRL-Y[esterday] will scroll screen by n lines down / up

 * / # will match whole word the cursor is on forward / backward
 g* / g# will also match words containing the word the cursor is on, g.e.: when on 'the', g* will match then there and so on.
 
=== VIM only

 :e $MYVIMRC

 While reading help or manual :set nu rnu    is useful

 :bp / :bn   or CTRL-O / CTRL-I  to go to the previous / next buffer

 v motion :w FILENAME   saves the Visually selected lines in file FILENAME 

 :set hls  highlights searched char string, :noh temporarilly removes highlight

 :set ic  highlights incremental search

 :set list / :set nolist turns invisible characters on / off

 command line completion with <TAB> is especially useful for :help

 Normal mode: ZZ is equivalent to :wq   ZZ also closes the help window without exiting the program

 Searching for text \< and \> are special markers that match beginning and end of a word

 After listing buffers :ls  close buffer n   with :bdn

 <TABS> or Ctrl-I goes to next jump, Ctrl-O

== From Quick Reference: see quickref.txt  :help quickref


=== matchit-configure

Configuration is local to the buffer (buffers could be of different languages, so different matching pairs).  So use :let instead of :set

== Get specific help


=== Normal mode command

 :help command_name
 :help x " shows delete one charj

=== Visual mode command

 prepend help with v_
 :help v_command_name
 :help v_u   " {Visual}u makes highlighted text lower case



=== Insert mode command

 prepend help with i_
 :help i_command_name
 :help i_<Esc>   " écrire litéralement <Esc> pour sortir de Insert ou Replace mode

=== Command-line command

 prepend help with :
 :help :command_name
 :help :quit

=== Command-line editing

 prepend help with c_
 :help c_command_name  " how to edit in the lower-screen command line
 :help c_<Del>

=== VIM command argument

 prepend help with -
 :help -command_name
 :help -r

=== Options

 prepend with '
 :help 'option'
 :help 'textwidth'

=== Regular expression
 
 prepend with /
 :help /reg_ex
 :help /[   " shows help on searching for character ranges


== VIM

 :scriptnames  " to see what files & plugins are loaded at startup

 :new
 :put=execute('scriptnames')  " will write in the new file

 VSCode will check in Settings (Ctrl+comma)  Vim> Vimrc:Path for vimrc file



== vimrc / .vimrc

in Linux Mint,  ~/.vim/vimrc contains one line:

 source ~/Documents/GitHub/cheat-sheet_VIM/vimrc 

== Managing packages (many plugins in a directory) and plugins

 https://vimhelp.org/repeat.txt.html#packages
 https://vi.stackexchange.com/questions/9522/what-is-the-vim8-package-feature-and-how-should-i-use-it
 https://medium.com/@paulodiovani/installing-vim-8-plugins-with-the-native-pack-system-39b71c351fea
